apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

resources:
- ../../base
- secret-store.yaml
- vault-token.yaml

namespace: staging

images:
- name: localhost/backend
  newName: localhost:5001/backend
  newTag: v1.0.0
- name: localhost/frontend
  newName: localhost:5001/frontend
  newTag: v1.0.0

patches:
- path: patch-ingress.yaml
