apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: staging

images:
- name: localhost/backend
  newName: localhost/backend:1,3
- name: localhost/frontend
  newName: localhost/frontend:1,8

patches:
- path: patch-ingress.yaml
