apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: mytest2

images:
- name: localhost/backend
  newName: localhost/backend:1,3
- name: localhost/frontend
  newName: localhost/frontend:1,8
- name: localhost:5001/backend
  newName: localhost:5001/backend
  newTag: v1.0.0
- name: localhost:5001/frontend
  newName: localhost:5001/frontend
  newTag: v1.0.0

patches:
- path: patch-ingress.yaml
