apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secret-store
spec:
  provider:
    vault:
      server: "http://host.docker.internal:8200"  # Mac → host.docker.internal
                                                   # Linux → IP del contenedor vault-local
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token      # Secret de K8s con el token de Vault
          key: token