apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-secret-store    # SecretStore definido en cada overlay
    kind: SecretStore
  target:
    name: backend-secrets       # nombre del Secret de K8s que ESO va a crear
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: staging/backend    # path en Vault — el overlay puede parcharlo
        property: DB_HOST
    - secretKey: SECRET_KEY
      remoteRef:
        key: staging/backend
        property: SECRET_KEY
    - secretKey: NAMESPACE
      remoteRef:
        key: staging/backend
        property: NAMESPACE