apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend/deployment.yaml
  - backend/deployment.yaml
  - backend/configmap.yaml
  - services.yaml
  - ingress.yaml

images:
  - name: localhost/frontend
    newTag: local
  - name: localhost/backend
    newTag: local
